Feature/mis compras
Capstone-user-app/user-app pull request #11
Opened 2022-10-03 17:16 UTC by Camila-sty

Esta funcionando el mockup server. Y se muestra bien la información del estado.

2022-10-03 17:32 UTC, vicentesh approved these changes

2022-10-03 17:40 UTC, vicentesh submitted a review, later dismissed
Terminar mis compras y dejar en una página aparte /mypurchases, además revisar que ocurre con netlify por que no carga las compras.
*nombres de archivos y variables deben ser en ingles según tengo entendido

2022-10-04 13:43 UTC, ignaciomansuy requested changes
Revisar los comentarios específicos que puse. También tener en consideración que la vista no está siendo responsiva para desktop (parece q los divs tienen un max-width)

2022-10-04 13:43 UTC, ignaciomansuy commented on src/components/infoState.js
> +const InfoState = (props) => {
Agregar un breve comentario en donde se especifique cual es el objetivo del componenete, de tal forma que el resto de los desarrolladores pueda determinar rápidamente (y sin tener q leer el código) si este componente les sirve o no

2022-10-04 13:43 UTC, ignaciomansuy commented on src/App.js
> +    <MisCompras />
Mis compras no tiene q ir en el landing page
en el landing page pongan un boton que lleve a localhost:3000/mis_compras

2022-10-05 20:53 UTC, lucgutm commented on src/components/infoState.js
> +const InfoState = (props) => {
están comentados los componentes ahora

2022-10-05 20:59 UTC, ignaciomansuy requested changes

2022-10-05 20:59 UTC, ignaciomansuy commented on src/index.js
> +          <Route path='/login' element={<Login />} />
este path no aplica, hay q sacarlo

2022-10-05 20:59 UTC, ignaciomansuy commented on src/index.js
> +          <Route path='/mypurchases' element={<MyPurchases />} />
los paths tienen q estar en español, en esta caso pon "/pedidos" porfa

2022-10-05 22:25 UTC, ignaciomansuy approved these changes

2022-10-05 22:28 UTC, merged