feat(auth0-implementation): basic auth0 implementation
Capstone-user-app/user-app pull request #7
Opened 2022-09-26 22:40 UTC by vicentesh

2022-09-27 18:22 UTC, ignaciomansuy requested changes

2022-09-27 18:22 UTC, ignaciomansuy commented on src/components/login.jsx
> +  // eslint-disable-next-line react/button-has-type, react/jsx-filename-extension
Estos eslitn disable hay q revisarlos, ya sea sacamos estas reglas del archivo linter o modificamos esto para adecuarnos a las reglas establecidas en el linter

2022-09-27 20:31 UTC, vicentesh commented on src/components/login.jsx
> +  // eslint-disable-next-line react/button-has-type, react/jsx-filename-extension
Quedó arreglado,  ahora se puede utilizar tanto .js, como .jsx.

2022-09-27 20:31 UTC, vicentesh commented on src/App.js
> +import Profile from './components/profile'
Completado, quedaron en la carpeta authetication

2022-09-28 12:22 UTC, ignaciomansuy approved these changes

2022-09-28 12:22 UTC, merged